#node-emulator2.toml
[server]
port = 5561

[node]
detect-drivers = false

[relay]
url = "http://localhost:4725"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\", \"appium:udid\": \"192.168.1.13:5555\", \"appium:automationName\": \"uiautomator2\"}"
]
