#node-emulator1.toml
[server]
port = 5555

[node]
detect-drivers = false

[relay]
url = "http://[2402:800:6341:fc8f:7136:edae:748a:86db]:4723"
status-endpoint = "/status"
protocol-version = "HTTP/1.1"
configs = [
    '1', '{"platformName": "android",  "appium:udid": "192.168.1.10:5555", "appium:automationName": "uiautomator2"}'
]
